require("generalConfigs")
require("configs/plugins/lsp")
require("mappings")
require("configs/plugins/explorer")
require("configs/plugins/colorscheme")
require("configs/plugins/statusline")
require("configs/plugins/bufferline")
