require("generalConfigs")
require("plugins")
require("mappings")
require("configs/plugins/explorer")
require("configs/plugins/colorscheme")
require("configs/plugins/statusline")
require("configs/plugins/bufferline")
require("configs/plugins/coc")
-- require("configs/plugins/autopair")
